# ---------------

In [ ]:
import pandas as pd
df_ts = pd.read_excel("SKU_final.xlsx")
df_hpp = pd.read_excel("/content/harga_brand_all_kategori_all_unsuspend_2026-06-18_14-29-34.xlsx")

cek hpp

In [ ]:
df_hpp["SKU"].duplicated().sum()

np.int64(0)

In [ ]:
print("HPP NaN:",df_hpp["HPP (Latest)"].isna().sum())
print("HPP = 0:",(df_hpp["HPP (Latest)"] == 0).sum())
print("HPP = 1:",(df_hpp["HPP (Latest)"] == 1).sum())

HPP NaN: 359
HPP = 0: 0
HPP = 1: 1616

In [ ]:
df_hpp[
    df_hpp["HPP (Latest)"] == 1
][
    ["SKU","Brand","Nama Accurate"]
].head(50)

,SKU,Brand,Nama Accurate
10,ACCUG0310-BC,UGREEN,Running Waist Belt UGreen Black (20818)
13,ACCUG0370,UGREEN,Hooks UGreen Adhesive (2-Pack) (10534)
21,ACCUG0092-BC,UGREEN,Pouch Phone UGreen Leather Waterproof - Black ...
25,ACPCL001,CLIPTEC,Cooling Pad CLIPtec RZC180 - 6 Fan with 2 USB ...
27,ACPCL003,CLIPTEC,Cooling Pad CLIPtec RZC190 - 6 Fan RGB with 2 ...
30,AMICCL001,CLIPTEC,Microphone Table Stand Multimedia Flexible CLI...
32,AWKCL002,CLIPTEC,WRISTPAD MOUSE CLIPTEC RZY309
33,CMCPUCRS0001,CORSAIR,CPU Cooler Corsair H100 RGB 240mm Liquid
35,CMCPUCRS0003,CORSAIR,CPU Cooler Corsair H100i iCUE RGB ELITE Liquid
36,ACCMS0001,MSI,Cooling Pad MSI MAG Coreliquid C240
37,BHD001,NO BRAND,"Baut HDD / SSD SATA / Motherboard 2,5 Inch"
38,BHD002,NO BRAND,"Baut HDD / SSD SATA / Motherboard 3,5 Inch"
39,HEORI0001,ORICO,"Enclosure Hardisk Orico 2,5 Inch SATA"
44,ACCTG0020,TARGUS,Targus DEFCON Resettable Combo Compact Cable L...
45,ACCTG0022,TARGUS,Master Key Targus DEFCON MKL Cable Lock ( ASK4...
46,ACCTG0023,TARGUS,CABLE LOCK TARGUS DEFCON N-CL COMBO ( ASP66APX )
47,ACCTG0024,TARGUS,Targus Security Anchor Base Plate - Silver ( ...
48,ACCTG0038,TARGUS,Kabel Lock Targus DEFCON MKL ( ASP48MKUSX-25 )
49,ACCTG0040,TARGUS,Targus Defcon MKL Cable Noble Lock With Key ( ...
53,ACCUG0079,UGREEN,Portable Stand UGreen Adjustable 4-9 Inch (30285)
58,ACCUG0084-BC,UGREEN,Tablet Stand UGreen Desktop - Black (20439)
59,ACCUG0085-BC,UGREEN,Foldable UGreen Phone Stand - Black (20435)
60,ACCUG0085-W,UGREEN,Foldable UGreen Phone Stand - White (20434)
74,ACCUG0248,UGREEN,Kabel Velcro UGreen 2M (40354)
81,BNS08,VIEWSONIC,Stylus Pen Viewsonic ACP501-B0WW
85,HTP 14.P,INFORCE,"SCREEN PROJECTOR INFORCE TRIPOD 1,78X1,78M"
87,HTP 16.P,INFORCE,SCREEN PROJECTOR INFORCE 120 Inch (3050X3050) ...
112,HTP 01.P,NO BRAND,SCREEN PROJECTOR TRIPOD 70 x 70mw
113,HTP 03.P,NO BRAND,SCREEN PROJECTOR CASA MOTORIZED MS84
116,HCPUA 106.P,ACER,PC AIO ACER C27-1751 / Core I5-1240P / Mem 8GB...
117,HCPUA 108.P,ACER,PC AIO ACER Veriton Z4 (VZ4/0032) / Core i5-12...
118,HCPUA 112.P,ACER,PC AIO ACER C24-1750 / Core I7-1260P / Mem 8GB...
120,HCPUA 116.P,ACER,PC AIO ACER C24-1751 / Core I7-1260P / Mem 8GB...
121,HCPUA 117.P,ACER,PC AIO ACER Veriton Z4 / Core i5-11400 / Mem 8...
126,HCPUA 98.P,ACER,PC AIO ACER C24-1751 / Core I5-1240P / Mem 8GB...
133,HCPUAS 204.P,ASUS,PC AIO ASUS A6432GAK-BA141W / CEL J4025 / Mem ...
135,HCPUAS 236.P-BC,ASUS,PC AIO ASUS A3202WBAK-BA585W / Core I5-1235U /...
136,HCPUAS 237.P-BC,ASUS,PC AIO ASUS A3402WBAT-BA585WS / Core I5-1235U ...
137,HCPUAS 238.P-BC,ASUS,PC AIO ASUS A3402WBAK-BA785WS / Core I7-1255U ...
138,HCPUAS 239.P-BC,ASUS,PC AIO ASUS A3402WBAT-BA785WS / Core I7-1255U ...
139,HCPUAS 242.P-BC,ASUS,PC AIO ASUS A3202WBAK-BA342W / Core I3-1215U /...
140,HCPUAS 243-BC,ASUS,PC AIO ASUS A3202WBAK-BA345W / Core I3-1215U /...
142,HCPUAS 245-W,ASUS,PC AIO ASUS A5402WVAT-WA711WS / Core I7-1360P ...
143,HCPUAS 247,ASUS,PC AIO ASUS A3202WBAK-BA382W / Core I3-1215U /...
144,HCPUAS 250,ASUS,PC AIO ASUS E3402WBAK-BA7805W / Core I7-1255U ...
145,HCPUAS 251.P,ASUS,PC AIO ASUS A5702WVAT-BA731WS / Core I7-1360P ...
146,HCPUAS 252.P,ASUS,PC AIO ASUS A3202WBAK-WA385W / Core I3-1215U /...
151,HCPUAS 262.P,ASUS,PC AIO ASUS A3402WBAT-WA515WS / Core I5-1235U ...
152,HCPUAS 263.P,ASUS,PC AIO ASUS A3402WBAK-WA715WS / Core I7-1255U ...
153,HCPUAS 264.P,ASUS,PC AIO ASUS E3402WBAK-BA785W / Core I7-1255U /...

In [ ]:
df_hpp_bermasalah = df_hpp[
    (df_hpp["HPP (Latest)"].isna())
    |
    (df_hpp["HPP (Latest)"] == 1)
][
    [
        "Nama Accurate",
        "SKU",
        "HPP (Latest)"
    ]
].copy()

print(df_hpp_bermasalah.shape)

df_hpp_bermasalah.to_excel("hpp_nan_dan_1.xlsx",index=False)

(1975, 3)

In [ ]:
print(
    "NaN:",
    df_hpp_bermasalah[
        df_hpp_bermasalah["HPP (Latest)"].isna()
    ].shape[0]
)

print(
    "HPP = 1:",
    df_hpp_bermasalah[
        df_hpp_bermasalah["HPP (Latest)"] == 1
    ].shape[0]
)

NaN: 359
HPP = 1: 1616

# New Section

In [ ]:
df_final = df_ts.merge(df_hpp, on="SKU", how="left")
print(df_ts.shape)
print(df_final.shape)

(8283, 9)
(8283, 18)

In [ ]:
print("HPP ditemukan:", df_final["HPP (Latest)"].notna().sum())
print(f"coverage HPP: {df_final['HPP (Latest)'].notna().mean() * 100:.2f}%")

HPP ditemukan: 5480
coverage HPP: 66.16%

In [ ]:
df_final[["Nama Produk","SKU","Brand","HPP (Latest)"]
].head(20)

,Nama Produk,SKU,Brand,HPP (Latest)
0,"Monitor VIEWSONIC VA22E2-H 22"" FHD VA 100Hz 5m...",MOVS0005-B008,NaN,NaN
1,Headset Gaming NYK Nemesis BEAST PRO W60 7.1 T...,AHSGNY0005,NYK NEMESIS,325000.0
2,Ugreen Kabel Converter Display Port To Hdtv 2M...,ACCUG0235-BC,UGREEN,99000.0
3,Rexus Keyboard Gaming Mecha Legionare Mx9 Tkl ...,AKYRX0006-BL,NaN,NaN
4,Aula Casing Pc Gaming Fz009 Atx Include 3 Fan ...,CPAU0002,AULA,350000.0
5,UGreen Wireless Bluetooth 2in1 Transmitter & R...,ACCUG0425,UGREEN,150000.0
6,Kabel UGreen 2 in 1 Dual USB-C Nylon Braided,ACCUG0409-BC,UGREEN,155000.0
7,Sony Headset Mdr-Ex155Ap Wired With Mic - Earp...,AHSSN0002-DBL,SONY,160000.0
8,Kabel Charger UGreen USB-C To USB-C 100W Nylon...,ACCUG0406-BL,UGREEN,55000.0
9,Armaggeddon Casing Tron Holo 5 Atx Rgb Hologra...,CPAR035-BC,NaN,NaN
10,Aula Mousepad Gaming Mp-Xl 900X400X3Mm - Mouse...,ACCAU0001,AULA,35000.0
11,Ugreen Ethernet Adapter Usb C 100Mbps Grey - U...,ACCUG0271,UGREEN,70000.0
12,TP Link PCI Express Adapter ARCHER T4E AC1200 ...,HRA80.P,NaN,NaN
13,Sandisk Micro Sd Max Endurance Sdhc 32Gb 100Mb...,MSS074,SANDISK,158600.0
14,Ugreen Mousepad 90564 Classic Rough 360X280X4M...,ACCUG0088-BC,UGREEN,45000.0
15,TP-Link Tapo C222 CCTV IP WIFI Camera 2K QHD 4...,HCMTP19,TPLINK,327273.0
16,Ugreen Enclosure Ssd Usb-C & Usb-A To M.2 Sata...,ACCUG0116,UGREEN,155000.0
17,Armaggeddon Casing Pc Aero Vii Atx+ Include Fa...,HCSPL102.P,NaN,NaN
18,Casing PC Gaming Armaggeddon Tritron 1 ATX wit...,CPAR044-BC,ARMAGGEDDON,341100.0
19,ACER Router Altos MT401 AX1500 Gigabit Dual Ba...,HRAC0001,ACER,200000.0

In [ ]:
df_hpp["HPP (Latest)"].isna().sum()
# Ensure SKUs are strings and non-null before creating sets
sku_ts = set(df_ts['SKU'].dropna().astype(str))
sku_hpp = set(df_hpp['SKU'].dropna().astype(str))
len(sku_ts - sku_hpp)

810

In [ ]:
print("SKU TS :", len(sku_ts))
print("SKU HPP:", len(sku_hpp))
print("SKU tidak ketemu:", len(sku_ts - sku_hpp))

SKU TS : 2493
SKU HPP: 6307
SKU tidak ketemu: 810

In [ ]:
sku_tidak_ketemu = sku_ts - sku_hpp

pd.DataFrame(
    sorted(list(sku_tidak_ketemu)),
    columns=["SKU"]
).head(50)

                   SKU
0           ACCBDP0001
1         ACCRX0001-BC
2            ACCUA0004
3            ACCUA0010
4   ACCVT0086-BC-FREE9
5              ADL01.P
6              ADL29.P
7                ADL32
8           AGPGL01-BD
9             AHSP17.P
10        AHSRX0002-SL
11             AJG12.P
12             AJG13.P
13             AJG17.P
14             AJG18.P
15             AJG22.P
16           AKBL21-MS
17            AKBV12.P
18         AKBV18.P-GO
19         AKBV21.P-GY
20            AKBV28.P
21            AKBV31.P
22            AKBV35.P
23            AKYP19.P
24            AKYP22.P
25            AKYP23.P
26            AKYP28.P
27            AKYP29.P
28            AKYP31.P
29            AKYP32.P
30         AKYP34.P-CL
31            AKYP35.P
32        AKYRX0006-BL
33           ALCDA21.P
34           ALCDA22.P
35           ALCDA24.P
36           ALCDA25.P
37     ALCDB20.P-BNS14
38     ALCDB21.P-BNS14
39     ALCDB22.P-BNS14
40     ALCDB26.P-BNS14
41           ALCDB27.P
42     ALCDV10.P-BNS14
43           AMI010-OL
44             AMP13.P
45             AMP16.P
46           AMP18.P-W
47             AMP19.P
48            AMSA05.P
49            AMSA06.P

In [ ]:
df_final["SKU_BASE"] = (

    df_final["SKU"]

    .astype(str)

    .str.split("-")

    .str[0]

)

In [ ]:
df_hpp["SKU_BASE"] = (

    df_hpp["SKU"]

    .astype(str)

    .str.split("-")

    .str[0]

)

In [ ]:
base_ts = set(
    df_final["SKU_BASE"]
)

base_hpp = set(
    df_hpp["SKU_BASE"]
)

print(
    "Base SKU yang tidak ketemu:",
    len(base_ts - base_hpp)
)

Base SKU yang tidak ketemu: 514

In [ ]:
sku_tidak_ketemu = list(
    sku_ts - sku_hpp
)

for s in sku_tidak_ketemu[:20]:
    print(s)

HMOMS25-B008
PCAIOLEN0006-B009
HCPUAS310.P-B012
HHST46.P
HCSPL78.P
TOPIWDBIRUHITAM
UAC0001-B008
HPROLGACI532.P
MOMSI0001-B012
HHST11.P
LML008-B008
HMBAS21.P
MOAOC0004-B012
LML050-B009
HMOLV24-B012
LMV011-B012
HLAWT19.P
HHST32.P
AKYP19.P
AMSA06.P

In [ ]:
df_hpp_ada = df_final[df_final["HPP (Latest)"].notna()]

print(df_hpp_ada.shape)

df_hpp_ada.to_excel("produk_ada_hpp.xlsx",index=False)

(5480, 19)

In [ ]:
print("Jumlah HPP = 1:",(df_hpp_ada["HPP (Latest)"] == 1).sum())
print("Produk unik HPP=1:",df_hpp_ada[df_hpp_ada["HPP (Latest)"] == 1]["SKU"].nunique())

Jumlah HPP = 1: 117
Produk unik HPP=1: 54

In [ ]:
df_hpp_ada[
    df_hpp_ada["HPP (Latest)"] == 1
][
    ["Nama Produk","SKU","HPP (Latest)"]
].head(20)

,Nama Produk,SKU,HPP (Latest)
40,Sandisk Ultra Shift CZ410 Flashdisk 64GB USB 3.2,FDS099,1.0
267,Alcatroz Casing Azzura Neox Mini-Atx With 450W...,CPAL035-BL,1.0
286,Ugreen Converter Display Port Male To Vga Fema...,ACCUG0294,1.0
299,Verbatim Mouse Wired Optical 1600 Dpi - Usb Op...,AMSV0001-BC,1.0
306,Infinity F126 Fan Casing RGB 12cm - Black (Loo...,ACCIF0001,1.0
307,Infinity F125 Fan Casing RGB 12cm - Black (Loo...,ACCIF0002,1.0
350,Ugreen Kabel Male To Male Usb-A 3.0 1M (10370)...,ACCUG0049,1.0
367,Anker Charger 511 Super Fast Charging Nano 3 3...,ACCANK0023-BC,1.0
412,Sonicgear Speaker Iox Bar Iii P + Speaker Soni...,BN0072,1.0
490,Flashdisk Lexar JumpDrive S47 32GB,FDLEX0006,1.0
511,Synology SNV3510-400G SSD NAS 400GB M.2 22110 ...,HSDSYN0001,1.0
814,Ugreen Kabel Lightning To Usb-C Nylon Braided ...,ACCUG0039,1.0
1118,Logitech M221 Mouse Wireless Silent,AMSL09-BL,1.0
1193,Tenveo Speakerphone Tevo-A3000B Portable Bluet...,TEV002,1.0
1259,Armaggeddon Kursi Gaming Premium Nebuka Iii - ...,HKGA006,1.0
1349,Wd Harddisk External Elements 4Tb 2.5 Inch - H...,HET017-S,1.0
1378,SonicGear Speaker Titan 2P (Passive) + Sonic B...,BN0135BT,1.0
1432,Vention Power Bank 10.000mAh 22.5W USB-C and 2...,ACCVT0097,1.0
1437,Ugreen Converter Display Port Male To Vga Fema...,ACCUG0294,1.0
1550,Targus Kabel Data Acc1011 Usb A To Microusb Us...,AKTG0007-GY,1.0

# hpp=1 dibuang

In [ ]:
df_hpp_ada_bersih = df_hpp_ada[df_hpp_ada["HPP (Latest)"] > 1].copy()

print(df_hpp_ada_bersih.shape)
print("Baris terhapus:",len(df_hpp_ada) - len(df_hpp_ada_bersih))
df_hpp_ada_bersih.to_excel("produk_ada_hpp_bersih.xlsx",index=False)

(5363, 19)
Baris terhapus: 117

# New Section

In [ ]:
df_hpp_tidak_ada = df_final[df_final["HPP (Latest)"].isna()]
S
print(df_hpp_tidak_ada.shape)

df_hpp_tidak_ada.to_excel("produk_tidak_ada_hpp.xlsx",index=False)

(2803, 19)

In [ ]:
contoh = "HAPT05.P"

df_hpp[
    df_hpp["SKU"]
    .astype(str)
    .str.contains(
        "HAPT05",
        na=False
    )
][["SKU"]]

Empty DataFrame
Columns: [SKU]
Index: []

In [ ]:
contoh = "HMOMS05W-B012"

df_hpp[
    df_hpp["SKU"]
    .astype(str)
    .str.contains(
        "HMOMS05W",
        na=False
    )
][["SKU"]]

Empty DataFrame
Columns: [SKU]
Index: []

In [ ]:
sku_ts = set(df_final["SKU"].dropna().astype(str))
sku_hpp = set(df_hpp["SKU"].dropna().astype(str))

sku_ts_not_found = sku_ts - sku_hpp

In [ ]:
df_sku_ts_not_found = pd.DataFrame({"SKU": sorted(list(sku_ts_not_found))})
# df_sku_ts_not_found = df_sku_ts_not_found.merge(df_ts[['SKU', 'Nama Produk']], on='SKU', how='left')
print(df_sku_ts_not_found.shape)
df_sku_ts_not_found.head()
# df_sku_ts_not_found.to_excel("sku_ts_tidak_ada_di_hpp.xlsx",index=False)

(810, 1)

                  SKU
0          ACCBDP0001
1        ACCRX0001-BC
2           ACCUA0004
3           ACCUA0010
4  ACCVT0086-BC-FREE9

In [ ]:
sku_hpp_not_found = sku_hpp - sku_ts
df_sku_hpp_not_found = pd.DataFrame({

    "SKU_HPP":
        sorted(
            list(sku_hpp_not_found)
        )

})

print(df_sku_hpp_not_found.shape)
# df_sku_hpp_not_found.to_excel("sku_hpp_tidak_ada_di_ts.xlsx",index=False)

(4624, 1)

In [ ]:
df_compare = pd.DataFrame({

    "SKU_TS_Tidak_Ketemu":

        pd.Series(
            sorted(
                list(sku_ts_not_found)
            )
        ),

    "SKU_HPP_Tidak_Ketemu":

        pd.Series(
            sorted(
                list(sku_hpp_not_found)
            )
        )

})

df_compare.to_excel("perbandingan_sku_ts_vs_hpp.xlsx",index=False)
print(df_compare.shape)

(4624, 2)

In [ ]:
df_produk_ts_tidak_match = (

    df_final[
        df_final["SKU"]
        .isin(sku_ts_not_found)
    ]

    [["Nama Produk","SKU"]]

)

df_produk_ts_tidak_match.to_excel("produk_ts_tidak_match.xlsx",index=False)
print(df_produk_ts_tidak_match.shape)

(2665, 2)

In [ ]:
sku_hpp_not_found = sku_hpp - sku_ts

df_produk_hpp_not_match = (

    df_hpp[
        df_hpp["SKU"]
        .isin(sku_hpp_not_found)
    ]

    [
        [
            "SKU",
            "Nama Accurate",
            "Brand"
        ]
    ]

    .drop_duplicates()

)

df_produk_hpp_not_match.to_excel(
    "produk_hpp_tidak_match_ts.xlsx",
    index=False
)

print(df_produk_hpp_not_match.shape)

(4620, 3)

In [ ]:
sku_ts_not_found = sku_ts - sku_hpp

investigasi = (

    df_final[
        df_final["SKU"]
        .isin(sku_ts_not_found)
    ]

    [
        [
            "Nama Produk",
            "clean_name",
            "SKU"
        ]
    ]

    .drop_duplicates()

    .sort_values("SKU")

)

investigasi.to_excel(
    "investigasi_sku_tidak_ketemu_hpp.xlsx",
    index=False
)

# cek coverage setelah normalisasi

In [ ]:
import re

def clean_sku(x):

    x = str(x).upper()

    x = re.sub(
        r'-.*$',
        '',
        x
    )

    x = re.sub(
        r'\.P$',
        '',
        x
    )

    return x.strip()

df_final["SKU_BASE"] = (
    df_final["SKU"]
    .apply(clean_sku)
)

df_hpp["SKU_BASE"] = (
    df_hpp["SKU"]
    .apply(clean_sku)
)

In [ ]:
base_ts = set(
    df_final["SKU_BASE"]
)

base_hpp = set(
    df_hpp["SKU_BASE"]
)

print(
    "Masih tidak ketemu:",
    len(base_ts - base_hpp)
)

Masih tidak ketemu: 512

# bikin ts ada di hpp

In [ ]:
df_hpp_only = (

    df_hpp[
        df_hpp["SKU"]
        .isin(sku_hpp_not_found)
    ]

    .copy()

)

df_hpp_only["Datetime"] = pd.Timestamp(
    "2026-05-05"
)

df_hpp_only["Harga"] = None
df_hpp_only["Qty"] = None
df_hpp_only["Omset (bln)"] = None
df_hpp_only["Qty (mg)"] = None
df_hpp_only["Omset (mg)"] = None

df_hpp_only["clean_name"] = (df_hpp_only["Nama Accurate"])
df_hpp_only.to_excel("produk_hpp_ditambah_timeseries.xlsx",index=False)

# bikin hpp ada di ts

In [ ]:
!pip install rapidfuzz

Collecting rapidfuzz
  Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 11.8 MB/s eta 0:00:00
Installing collected packages: rapidfuzz
Successfully installed rapidfuzz-3.14.5

In [ ]:
from rapidfuzz import process, fuzz
import pandas as pd

# Produk yang belum punya HPP
df_hpp_tidak_ada = df_final[
    df_final["HPP (Latest)"].isna()
].copy()

print(df_hpp_tidak_ada.shape)

# List SKU dari portal HPP
sku_hpp_list = (
    df_hpp["SKU"]
    .dropna()
    .astype(str)
    .unique()
)

hasil = []

for idx, row in df_hpp_tidak_ada.iterrows():

    sku_ts = str(row["SKU"])

    kandidat = process.extractOne(
        sku_ts,
        sku_hpp_list,
        scorer=fuzz.ratio
    )

    if kandidat:

        hasil.append([
            row["Nama Produk"],
            sku_ts,
            kandidat[0],      # SKU HPP kandidat
            kandidat[1]       # Similarity score
        ])

df_fuzzy = pd.DataFrame(
    hasil,
    columns=[
        "Nama Produk",
        "SKU_TS",
        "SKU_HPP_Kandidat",
        "Similarity"
    ]
)

# Ambil yang similarity >= 98%
df_fuzzy_98 = df_fuzzy[
    df_fuzzy["Similarity"] >= 60
]

print(df_fuzzy_98.shape)

# df_fuzzy_98.to_excel(
#     "hpp_kandidat_similarity_98.xlsx",
#     index=False
# )

(2803, 19)
(2781, 4)

In [ ]:
# Lihat statistik similarity
print(df_fuzzy["Similarity"].describe())

count    2803.000000
mean       83.408201
std        11.812602
min         0.000000
25%        72.727273
50%        83.720930
75%        94.117647
max       100.000000
Name: Similarity, dtype: float64

In [ ]:
print(
    df_fuzzy["Similarity"]
    .value_counts()
    .sort_index(ascending=False)
    .head(20)
)

Similarity
100.000000    135
97.560976       1
96.551724      58
96.000000       5
95.652174      23
95.238095      20
95.000000       1
94.736842     254
94.117647     408
93.333333     355
92.857143       6
92.307692       3
91.666667      11
90.909091       2
90.000000       7
88.888889       9
88.372093       5
88.000000      14
87.500000      33
86.956522       4
Name: count, dtype: int64

In [ ]:
df_fuzzy_98 = df_fuzzy_98.merge(

    df_hpp[
        [
            "SKU",
            "HPP (Latest)"
        ]
    ],

    left_on="SKU_HPP_Kandidat",
    right_on="SKU",
    how="left"

)

In [ ]:
df_fuzzy_98.to_excel("hpp_kandidat_similarity_98.xlsx",index=False)